name: Build Only

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: wykies/checkout@main
        with:
          submodules: recursive
      - name: Build only
        uses: wykies/zola-deploy-action@upgrade_to_zola_19
        env:
          OUT_DIR: docs
          BUILD_DIR: .
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}