name: Check Links

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'config.toml'
  schedule:
    - cron: '0 0 25 * *' # Run once a month on the 25th at midnight UTC

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: wykies/checkout@main
        with:
          submodules: recursive
      - uses: taiki-e/install-action@main
        with:
          tool: zola
      - name: Show version information
        shell: bash
        run: zola --version
      - name: Run check
        run:  zola check
  